### PR TITLE
add dependencyCheckAnalyze on the jenkins pipeline

### PR DESCRIPTION
**Pull request by alexsoliri**
#48 work around to make sure that pull request pass that test at least.

### CODE REVIEW

**Comment by alexsoliri** [comment]
Please don't kill the messenger, I have just turned on the test. The app was failing it before.
The d3js lib is embedding with hystrix-dashboard.

I would suggest to removed the whole hystrix from the template as it is not mandatory and looks specific. Do you want me to do that?

**Comment by timja** [comment]
Its great to turn it on, but to merge it we need to fix the issue.
@rkondratowicz / @nitinprabhu  thoughts on removing hystrix?

**Comment by doncem** [comment]
We only use CircuitBreaker from the library. I doubt any one used dashboard. Since d3js is dashboard related, I suggest removing relevant dependency by just leaving hystrix alone. Therefore having the benefit of automatic CircuitBreaker functionality

**Comment by doncem** [comment]
this repository has a nightly build now #53

**Pull request closed without merging**
